# Consolidate the common configuration for reuse across multiple steps.
definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
    retry:
      manual:
        permit_on_passed: true
  plugins:
    ecr: &ecr
      ecr#v2.7.0:
        login: true
        no-include-email: true
    forumone-extract: &forumone-extract
      forumone/extract#v0.2.0:
        image: ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}
        from: /var/www/html
        to: ${ARTIFACT_LOCATION}
  git-remote-repo: &git-remote-repo
    remote: [ACQUIA GIT REPO]
  ssh-defaults: &ssh-defaults
    ssh:
      keyscan: [ACQUIA HOST]
  git: &git
    git:
      name: F1 Builder
      email: support+f1builder@forumone.com
  files: &files
    files:
      force-add:
        - vendor
        - docroot
        - docroot/sites/default/settings.php
  # This will only trigger when the build branch is: live, main, or integration
  # and NOT a PR
  # build.pull_request.base_branch == null ; refers to the PR code is being merged into
  deploy-release-conditional: &deploy-release-conditional
    if: |
      build.pull_request.base_branch == null
      && (
        build.branch == 'live'
        || build.branch == 'main'
        || build.branch == 'integration'
      )
steps:
  - label: ":git: Deploy"
    depends_on: "building-image"
    <<: *step-defaults
    concurrency: 1
    concurrency_group: '$BUILDKITE_PIPELINE_SLUG/$BUILDKITE_BRANCH/deploy'
    <<: *deploy-release-conditional
    plugins:
      # Log into ECR for this build step to access and push images.
      - *ecr

      # Download the prebuilt image and extract project files to the
      # local filesystem for further operations.
      - *forumone-extract

      # Execute an artifact deployment using the defined branch to
      # environment mapping.
      - forumone/artifact-push#v0.3.1:
          verbose: false
          source-directory: ${ARTIFACT_LOCATION}
          <<: *git-remote-repo
          branches:
            - match: integration
              target: integration
            - match: main
              target: main
            - match: live
              target: live
          <<: *ssh-defaults
          <<: *git
          <<: *files
